// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const SwaggerTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/v1/auth/changePassword": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "当前登录管理员通过旧密码修改登录密码",
                "tags": [
                    "认证管理"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.ChangePasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/v1/auth/getUserInfo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据上下文中的管理员ID获取当前登录用户的详细信息",
                "tags": [
                    "认证管理"
                ],
                "summary": "获取当前登录用户信息",
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/v1/auth/login": {
            "post": {
                "description": "使用用户名/密码登录管理员账号，可选验证码校验，返回访问令牌与刷新令牌",
                "tags": [
                    "认证管理"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "当前登录管理员退出登录，注销访问令牌",
                "tags": [
                    "认证管理"
                ],
                "summary": "退出登录",
                "responses": {
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/v1/auth/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取当前登录管理员的个人资料信息",
                "tags": [
                    "认证管理"
                ],
                "summary": "获取个人资料",
                "responses": {
                    "200": {
                        "description": "个人资料",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新当前登录管理员的个人资料，例如昵称、手机号、邮箱、性别",
                "tags": [
                    "认证管理"
                ],
                "summary": "更新个人资料",
                "parameters": [
                    {
                        "description": "个人资料信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.UpdateProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/v1/auth/refreshToken": {
            "post": {
                "description": "使用刷新令牌换取新的访问令牌与刷新令牌",
                "tags": [
                    "认证管理"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.RefreshTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/v1/system/configs": {
            "get": {
                "description": "根据组名获取多项配置，例如 cache_switches",
                "tags": [
                    "系统配置管理"
                ],
                "summary": "获取配置分组",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置组名",
                        "name": "groupName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "配置列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/system.SysConfigVO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新缓存开关或其他动态配置，修改后自动通过Redis广播全局重新加载内存字典",
                "tags": [
                    "系统配置管理"
                ],
                "summary": "更新/新增单个系统配置",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.UpdateConfigReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "保存成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/v1/system/test-email": {
            "post": {
                "description": "使用当前邮件配置发送测试邮件，验证配置是否正确",
                "tags": [
                    "系统配置管理"
                ],
                "summary": "测试邮件发送",
                "parameters": [
                    {
                        "description": "测试邮件信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system.TestEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "发送成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "captchaId": {
                    "type": "string"
                },
                "captchaValue": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "userName": {
                    "type": "string",
                    "example": "admin"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {},
                "data": {},
                "msg": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "system.ChangePasswordReq": {
            "type": "object",
            "properties": {
                "newPassword": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "oldPassword": {
                    "type": "string"
                }
            }
        },
        "system.RefreshTokenReq": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "system.SysConfigVO": {
            "type": "object"
        },
        "system.TestEmailReq": {
            "type": "object"
        },
        "system.UpdateConfigReq": {
            "type": "object"
        },
        "system.UpdateProfileReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 100
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "0",
                        "1",
                        "2"
                    ]
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo exported SwaggerInfo variable
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/admin/v1",
	Schemes:          []string{},
	Title:            "NetyAdmin API",
	Description:      "NetyAdmin 后台管理系统 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  SwaggerTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
