import { $t } from '@/locales';

export const BackendErrorCode = {
  invalidParams: '100001',
  unauthorized: '100002',
  forbidden: '100003',
  notFound: '100004',
  internalError: '100005',
  tooManyRequest: '100006',
  badRequest: '100007',
  alreadyExists: '100008',
  captchaWrong: '100009',
  captchaRequired: '100010',
  userNotFound: '101001',
  userDisabled: '101002',
  passwordWrong: '101003',
  userAlreadyExists: '101004',
  tokenExpired: '101005',
  tokenInvalid: '101006',
  oldPasswordWrong: '101007',
  roleNotFound: '102001',
  roleInUse: '102002',
  roleAlreadyExists: '102003',
  roleCodeDuplicate: '102004',
  cannotDeleteSuper: '102005',
  cannotModifySuper: '102006',
  menuNotFound: '103001',
  menuHasChildren: '103002',
  menuAlreadyExists: '103003',
  menuRouteDuplicate: '103004',
  buttonNotFound: '104001',
  buttonAlreadyExists: '104002',
  buttonCodeDuplicate: '104003',
  apiNotFound: '105001',
  apiAlreadyExists: '105002',
  apiPathDuplicate: '105003',
  // 用户模块 (1011xx)
  clientUserNotFound: '101101',
  clientUserAlreadyExists: '101102',
  emailAlreadyExists: '101103',
  phoneAlreadyExists: '101104',
  // 消息模块 (1012xx)
  msgTemplateNotFound: '101201',
  msgTemplateCodeExists: '101202',
  msgSendFailed: '101203',
  msgRecordNotFound: '101204',
  msgDriverNotFound: '101205',
  // 开放平台 (1013xx)
  appKeyInvalid: '101301',
  signatureFailed: '101302',
  requestExpired: '101303',
  scopeMismatch: '101304',
  rateLimited: '101305',
  // IP 访问控制 (1014xx)
  ipBlocked: '101401',
  ipInvalid: '101402',
  whitelistMode: '101403',
  // 用户模块集成 (2006xx)
  captchaExpired: '200601',
  captchaSendTooFrequent: '200604',
  verifyTypeNotConfigured: '200605'
} as const;

const backendErrorI18nKeyMap: Record<string, string> = {
  [BackendErrorCode.invalidParams]: 'request.backend.invalidParams',
  [BackendErrorCode.unauthorized]: 'request.backend.unauthorized',
  [BackendErrorCode.forbidden]: 'request.backend.forbidden',
  [BackendErrorCode.notFound]: 'request.backend.notFound',
  [BackendErrorCode.internalError]: 'request.backend.internalError',
  [BackendErrorCode.tooManyRequest]: 'request.backend.tooManyRequest',
  [BackendErrorCode.badRequest]: 'request.backend.badRequest',
  [BackendErrorCode.alreadyExists]: 'request.backend.alreadyExists',
  [BackendErrorCode.captchaWrong]: 'request.backend.captchaWrong',
  [BackendErrorCode.captchaRequired]: 'request.backend.captchaRequired',
  [BackendErrorCode.userNotFound]: 'request.backend.userNotFound',
  [BackendErrorCode.userDisabled]: 'request.backend.userDisabled',
  [BackendErrorCode.passwordWrong]: 'request.backend.passwordWrong',
  [BackendErrorCode.userAlreadyExists]: 'request.backend.userAlreadyExists',
  [BackendErrorCode.tokenExpired]: 'request.backend.tokenExpired',
  [BackendErrorCode.tokenInvalid]: 'request.backend.tokenInvalid',
  [BackendErrorCode.oldPasswordWrong]: 'request.backend.oldPasswordWrong',
  [BackendErrorCode.roleNotFound]: 'request.backend.roleNotFound',
  [BackendErrorCode.roleInUse]: 'request.backend.roleInUse',
  [BackendErrorCode.roleAlreadyExists]: 'request.backend.roleAlreadyExists',
  [BackendErrorCode.roleCodeDuplicate]: 'request.backend.roleCodeDuplicate',
  [BackendErrorCode.cannotDeleteSuper]: 'request.backend.cannotDeleteSuper',
  [BackendErrorCode.cannotModifySuper]: 'request.backend.cannotModifySuper',
  [BackendErrorCode.menuNotFound]: 'request.backend.menuNotFound',
  [BackendErrorCode.menuHasChildren]: 'request.backend.menuHasChildren',
  [BackendErrorCode.menuAlreadyExists]: 'request.backend.menuAlreadyExists',
  [BackendErrorCode.menuRouteDuplicate]: 'request.backend.menuRouteDuplicate',
  [BackendErrorCode.buttonNotFound]: 'request.backend.buttonNotFound',
  [BackendErrorCode.buttonAlreadyExists]: 'request.backend.buttonAlreadyExists',
  [BackendErrorCode.buttonCodeDuplicate]: 'request.backend.buttonCodeDuplicate',
  [BackendErrorCode.apiNotFound]: 'request.backend.apiNotFound',
  [BackendErrorCode.apiAlreadyExists]: 'request.backend.apiAlreadyExists',
  [BackendErrorCode.apiPathDuplicate]: 'request.backend.apiPathDuplicate',
  // 用户模块 (1011xx)
  [BackendErrorCode.clientUserNotFound]: 'request.backend.clientUserNotFound',
  [BackendErrorCode.clientUserAlreadyExists]: 'request.backend.clientUserAlreadyExists',
  [BackendErrorCode.emailAlreadyExists]: 'request.backend.emailAlreadyExists',
  [BackendErrorCode.phoneAlreadyExists]: 'request.backend.phoneAlreadyExists',
  // 消息模块 (1012xx)
  [BackendErrorCode.msgTemplateNotFound]: 'request.backend.msgTemplateNotFound',
  [BackendErrorCode.msgTemplateCodeExists]: 'request.backend.msgTemplateCodeExists',
  [BackendErrorCode.msgSendFailed]: 'request.backend.msgSendFailed',
  [BackendErrorCode.msgRecordNotFound]: 'request.backend.msgRecordNotFound',
  [BackendErrorCode.msgDriverNotFound]: 'request.backend.msgDriverNotFound',
  // 开放平台 (1013xx)
  [BackendErrorCode.appKeyInvalid]: 'request.backend.appKeyInvalid',
  [BackendErrorCode.signatureFailed]: 'request.backend.signatureFailed',
  [BackendErrorCode.requestExpired]: 'request.backend.requestExpired',
  [BackendErrorCode.scopeMismatch]: 'request.backend.scopeMismatch',
  [BackendErrorCode.rateLimited]: 'request.backend.rateLimited',
  // IP 访问控制 (1014xx)
  [BackendErrorCode.ipBlocked]: 'request.backend.ipBlocked',
  [BackendErrorCode.ipInvalid]: 'request.backend.ipInvalid',
  [BackendErrorCode.whitelistMode]: 'request.backend.whitelistMode',
  // 用户模块集成 (2006xx)
  [BackendErrorCode.captchaExpired]: 'request.backend.captchaExpired',
  [BackendErrorCode.captchaSendTooFrequent]: 'request.backend.captchaSendTooFrequent',
  [BackendErrorCode.verifyTypeNotConfigured]: 'request.backend.verifyTypeNotConfigured'
};

export function getBackendErrorMessage(code: string) {
  const i18nKey = code ? backendErrorI18nKeyMap[code] : '';
  return $t(i18nKey || 'request.backend.unknown');
}
