-- 0042_seed_sys_configs.down.sql
-- 回滚 0042：删除种子初始化的系统配置（按 group_name + config_key 精确匹配）
DELETE FROM sys_configs
WHERE (group_name, config_key) IN (
    -- email_config
    ('email_config', 'enabled'),
    ('email_config', 'host'),
    ('email_config', 'port'),
    ('email_config', 'user'),
    ('email_config', 'password'),
    ('email_config', 'from'),
    ('email_config', 'ssl_enabled'),
    ('email_config', 'auth_type'),
    ('email_config', 'starttls_enabled'),
    ('email_config', 'connect_timeout'),
    ('email_config', 'send_timeout'),
    -- sms_config
    ('sms_config', 'enabled'),
    ('sms_config', 'driver'),
    ('sms_config', 'secret_id'),
    ('sms_config', 'secret_key'),
    ('sms_config', 'app_id'),
    ('sms_config', 'sign_name'),
    -- msg_record_config
    ('msg_record_config', 'retention_days'),
    -- captcha_config
    ('captcha_config', 'admin_login_enabled'),
    ('captcha_config', 'user_register_enabled'),
    ('captcha_config', 'user_login_enabled'),
    ('captcha_config', 'captcha_length'),
    ('captcha_config', 'captcha_width'),
    ('captcha_config', 'captcha_height'),
    ('captcha_config', 'captcha_type'),
    ('captcha_config', 'captcha_expire'),
    ('captcha_config', 'user_reset_pwd_captcha_enabled'),
    -- cache_switches
    ('cache_switches', 'captcha'),
    ('cache_switches', 'rbac_auth'),
    ('cache_switches', 'sys_config'),
    ('cache_switches', 'rbac_menu'),
    ('cache_switches', 'admin'),
    ('cache_switches', 'dict'),
    ('cache_switches', 'storage'),
    ('cache_switches', 'err_log_cache'),
    ('cache_switches', 'content_category_cache'),
    ('cache_switches', 'content_article_cache'),
    ('cache_switches', 'content_banner_cache'),
    -- task_config
    ('task_config', 'log_enabled'),
    ('task_config', 'retention_days'),
    ('task_config', 'task:article_publish:enabled'),
    -- ops_config
    ('ops_config', 'retention_days'),
    -- error_config
    ('error_config', 'retention_days'),
    -- user_config
    ('user_config', 'storage_module'),
    ('user_config', 'login_storage'),
    ('user_config', 'token_expire'),
    ('user_config', 'login_max_retry'),
    ('user_config', 'login_lock_duration'),
    ('user_config', 'password_min_length'),
    ('user_config', 'password_require_types'),
    ('user_config', 'user_register_verify'),
    ('user_config', 'user_register_verify_type'),
    ('user_config', 'user_login_verify'),
    ('user_config', 'user_login_verify_type'),
    ('user_config', 'user_reset_pwd_verify'),
    ('user_config', 'user_reset_pwd_verify_type'),
    -- open_platform_config
    ('open_platform_config', 'log_retention_days'),
    ('open_platform_config', 'default_rate'),
    ('open_platform_config', 'default_capacity'),
    -- content_cache
    ('content_cache', 'banner_cache_ttl'),
    ('content_cache', 'category_cache_ttl'),
    ('content_cache', 'article_cache_ttl'),
    -- logbus_config
    ('logbus_config', 'global_max_entries'),
    ('logbus_config', 'global_max_bytes_mb'),
    ('logbus_config', 'default_batch_size'),
    ('logbus_config', 'default_time_threshold'),
    ('logbus_config', 'operation_batch_size'),
    ('logbus_config', 'operation_time_threshold'),
    ('logbus_config', 'error_batch_size'),
    ('logbus_config', 'error_time_threshold'),
    ('logbus_config', 'open_batch_size'),
    ('logbus_config', 'open_time_threshold'),
    ('logbus_config', 'task_batch_size'),
    ('logbus_config', 'task_time_threshold'),
    ('logbus_config', 'force_sync')
);
